/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Georgia14.c                                           *
* Font:        Georgia                                               *
* Height:      14                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  14                                           *
*                                                                    *
**********************************************************************
*/
#include "myFont.h"
//#include "Georgia14.h"

/* Start of unicode area <Basic Latin> */
const unsigned char acGUI_FontGeorgia14_0020[ 14] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0021[ 14] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  _X______,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0022[ 14] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0023[ 14] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  ___X_X__,
  ___X_X__,
  XXXXXXX_,
  __X_X___,
  __X_X___,
  XXXXXXX_,
  _X_X____,
  _X_X____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0024[ 14] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXXX__,
  _X_X_X__,
  _X_X____,
  __XX____,
  ___XX___,
  ___X_X__,
  _X_X_X__,
  _XXXX___,
  ___X____,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0025[ 28] = { /* code 0025, PERCENT SIGN */
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  _X__X__X,________,
  _X__X_X_,________,
  __XX_X__,________,
  ____X_XX,________,
  ___X_X__,X_______,
  __X__X__,X_______,
  ______XX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0026[ 14] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  _XX__XX_,
  X__X_X__,
  X___X___,
  X___X___,
  _XXX_XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0027[ 14] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0028[ 14] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  __XX____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __XX____,
  ________};

const unsigned char acGUI_FontGeorgia14_0029[ 14] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  XX______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  XX______,
  ________};

const unsigned char acGUI_FontGeorgia14_002A[ 14] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  _X_X____,
  __X_____,
  XXXXX___,
  __X_____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_002B[ 14] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_002C[ 14] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  __X_____,
  _X______,
  ________};

const unsigned char acGUI_FontGeorgia14_002D[ 14] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_002E[ 14] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_002F[ 14] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______};

const unsigned char acGUI_FontGeorgia14_0030[ 14] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0031[ 14] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0032[ 14] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  ______X_,
  ___XXX__,
  __X_____,
  _XXXXXX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0033[ 14] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  ______X_,
  ___XXX__,
  ______X_,
  ______X_,
  _X____X_,
  __XXXX__,
  ________};

const unsigned char acGUI_FontGeorgia14_0034[ 14] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ________};

const unsigned char acGUI_FontGeorgia14_0035[ 14] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  __X_____,
  __X_____,
  __XXXX__,
  ______X_,
  ______X_,
  _X____X_,
  __XXXX__,
  ________};

const unsigned char acGUI_FontGeorgia14_0036[ 14] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ____X___,
  ___X____,
  __X_____,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0037[ 14] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X____X_,
  _X___X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ________};

const unsigned char acGUI_FontGeorgia14_0038[ 14] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0039[ 14] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  _____X__,
  ____X___,
  ___X____,
  ________};

const unsigned char acGUI_FontGeorgia14_003A[ 14] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_003B[ 14] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  _XX_____,
  __X_____,
  __X_____,
  _X______,
  ________};

const unsigned char acGUI_FontGeorgia14_003C[ 14] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _____X__,
  ___XX___,
  _XX_____,
  ___XX___,
  _____X__,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_003D[ 14] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ________,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_003E[ 14] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  __XX____,
  ____XX__,
  __XX____,
  _X______,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_003F[ 14] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  ________,
  __X_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0040[ 28] = { /* code 0040, COMMERCIAL AT */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  ___X____,X_______,
  __X__XXX,_X______,
  _X__X__X,_X______,
  _X_X__X_,_X______,
  _X_X__X_,_X______,
  _X_X__X_,_X______,
  _X__XX_X,X_______,
  __X_____,________,
  ___XXXXX,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0041[ 28] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0042[ 14] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  XXXXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0043[ 14] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  X_____X_,
  X_______,
  X_______,
  X_______,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0044[ 14] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0045[ 14] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X___X__,
  _X______,
  _XXXX___,
  _X______,
  _X___X__,
  _X___X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0046[ 14] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X___X__,
  _X______,
  _X______,
  _XXXX___,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0047[ 28] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  _X____X_,________,
  X_____X_,________,
  X_______,________,
  X____XXX,________,
  X_____X_,________,
  _X____X_,________,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0048[ 28] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  _X_____X,________,
  _X_____X,________,
  _XXXXXXX,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  XXX___XX,X_______,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0049[ 14] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_004A[ 14] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  __XXX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_004B[ 14] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  XXX__XX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X__X___,
  _X___X__,
  XXX__XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_004C[ 14] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X___X__,
  _X___X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_004D[ 28] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  _XX___XX,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X_____X,________,
  XXX___XX,X_______,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_004E[ 28] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  XX___XXX,________,
  _XX___X_,________,
  _X_X__X_,________,
  _X_X__X_,________,
  _X__X_X_,________,
  _X__X_X_,________,
  _X___XX_,________,
  XXX___X_,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_004F[ 28] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0050[ 14] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0051[ 28] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ____X___,________,
  _____XXX,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0052[ 14] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X__X___,
  _X___X__,
  XXX__XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0053[ 14] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  _XXXXX__,
  X____X__,
  X____X__,
  _XX_____,
  ___XX___,
  X____X__,
  X____X__,
  XXXXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0054[ 14] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0055[ 28] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0056[ 28] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  _X____X_,________,
  __X__X__,________,
  __X__X__,________,
  __X__X__,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0057[ 28] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  XXX__X__,XXX_____,
  _X___X__,_X______,
  _X___X__,_X______,
  __X_X_X_,X_______,
  __X_X_X_,X_______,
  __X_X_X_,X_______,
  ___X___X,________,
  ___X___X,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0058[ 28] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  __X__X__,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0059[ 14] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_005A[ 14] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  XXXXXX__,
  X____X__,
  X___X___,
  ___X____,
  __X_____,
  _X___X__,
  X____X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_005B[ 14] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ________,
  _XXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXX____,
  ________};

const unsigned char acGUI_FontGeorgia14_005C[ 14] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____};

const unsigned char acGUI_FontGeorgia14_005D[ 14] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_005E[ 14] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  _X___X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_005F[ 14] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________};

const unsigned char acGUI_FontGeorgia14_0060[ 14] = { /* code 0060, GRAVE ACCENT */
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0061[ 14] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0062[ 14] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0063[ 14] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___X___,
  X_______,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0064[ 14] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ___XX___,
  ____X___,
  ____X___,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0065[ 14] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  __XX____,
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0067[ 14] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  X___X___,
  X___X___,
  _XXX____,
  _X______,
  _XXXXX__,
  X____X__,
  XXXXX___,
  ________};

const unsigned char acGUI_FontGeorgia14_0068[ 14] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0069[ 14] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  _X______,
  ________,
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_006A[ 14] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  _X______,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  ________};

const unsigned char acGUI_FontGeorgia14_006B[ 14] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X__XX__,
  _X__X___,
  _XXX____,
  _X_X____,
  _X__X___,
  XXX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_006D[ 28] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX_XX__X,X_______,
  _XX__XX_,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  XXX_XXX_,XXX_____,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_006E[ 14] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_006F[ 14] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0070[ 14] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_0071[ 14] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  ___XXX__,
  ________};

const unsigned char acGUI_FontGeorgia14_0072[ 14] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX_X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0073[ 14] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X__X____,
  XX______,
  __XX____,
  X__X____,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0074[ 14] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  __XX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0075[ 14] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0076[ 14] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0077[ 28] = { /* code 0077, LATIN SMALL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__X__X,X_______,
  _X__X__X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  __X___X_,________,
  __X___X_,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_0078[ 14] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  _X__X___,
  __XX____,
  __XX____,
  _X__X___,
  XX__XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_0079[ 14] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  _XX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_007A[ 14] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  X__X____,
  __X_____,
  _X______,
  X__X____,
  XXXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_007B[ 14] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ________,
  ___XX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___,
  ________};

const unsigned char acGUI_FontGeorgia14_007C[ 14] = { /* code 007C, VERTICAL LINE */
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________};

const unsigned char acGUI_FontGeorgia14_007D[ 14] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  ________,
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______,
  ________};

const unsigned char acGUI_FontGeorgia14_007E[ 14] = { /* code 007E, TILDE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX__X_,
  _X__XX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Latin-1 Supplement> */
const unsigned char acGUI_FontGeorgia14_00A0[ 14] = { /* code 00A0, NO-BREAK SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00A1[ 14] = { /* code 00A1, INVERTED EXCLAMATION MARK */
  ________,
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00A2[ 14] = { /* code 00A2, CENT SIGN */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __XXXX__,
  _X_X____,
  _X_X____,
  _X_X____,
  _X_X____,
  __XXXX__,
  ___X____,
  ___X____,
  ________};

const unsigned char acGUI_FontGeorgia14_00A3[ 14] = { /* code 00A3, POUND SIGN */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  __X_____,
  __X_____,
  _XXXX___,
  __X_____,
  _X______,
  _XXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00A4[ 14] = { /* code 00A4, CURRENCY SIGN */
  ________,
  ________,
  ________,
  ________,
  X____X__,
  _XXXX___,
  _X__X___,
  _X__X___,
  _XXXX___,
  X____X__,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00A5[ 14] = { /* code 00A5, YEN SIGN */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  _XXXXX__,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00A6[ 14] = { /* code 00A6, BROKEN BAR */
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________};

const unsigned char acGUI_FontGeorgia14_00A7[ 14] = { /* code 00A7, SECTION SIGN */
  ________,
  ________,
  ________,
  _XXX____,
  X_______,
  X_______,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ___X____,
  ___X____,
  XXX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_00A8[ 14] = { /* code 00A8, DIAERESIS */
  ________,
  ________,
  ________,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00A9[ 28] = { /* code 00A9, COPYRIGHT SIGN */
  ________,________,
  ________,________,
  __XXXXX_,________,
  _X_____X,________,
  X__XXXX_,X_______,
  X_X___X_,X_______,
  X_X_____,X_______,
  X_X___X_,X_______,
  X__XXX__,X_______,
  _X_____X,________,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00AA[ 14] = { /* code 00AA, FEMININE ORDINAL INDICATOR */
  ________,
  ________,
  ________,
  __XX____,
  ____X___,
  __XXX___,
  _X__X___,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00AB[ 14] = { /* code 00AB, LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X_X__,
  __X_X___,
  _X_X____,
  __X_X___,
  ___X_X__,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00AC[ 14] = { /* code 00AC, NOT SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _____X__,
  _____X__,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00AD[ 14] = { /* code 00AD, SOFT HYPHEN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00AE[ 28] = { /* code 00AE, REGISTERED SIGN */
  ________,________,
  ________,________,
  __XXXXX_,________,
  _X_____X,________,
  X__XXX__,X_______,
  X__X__X_,X_______,
  X__XXX__,X_______,
  X__X_X__,X_______,
  X__X__X_,X_______,
  _X_____X,________,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00AF[ 14] = { /* code 00AF, MACRON */
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B0[ 14] = { /* code 00B0, DEGREE SIGN */
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B1[ 14] = { /* code 00B1, PLUS-MINUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B2[ 14] = { /* code 00B2, SUPERSCRIPT TWO */
  ________,
  ________,
  ________,
  _XXXX___,
  ____X___,
  ___X____,
  __X_____,
  _XXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B3[ 14] = { /* code 00B3, SUPERSCRIPT THREE */
  ________,
  ________,
  ________,
  _XXX____,
  ____X___,
  __XX____,
  ____X___,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B4[ 14] = { /* code 00B4, ACUTE ACCENT */
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B5[ 14] = { /* code 00B5, MICRO SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX_X__,
  _X______,
  _X______,
  ________};

const unsigned char acGUI_FontGeorgia14_00B6[ 14] = { /* code 00B6, PILCROW SIGN */
  ________,
  ________,
  ________,
  _XXXXX__,
  XXX_X___,
  XXX_X___,
  XXX_X___,
  _XX_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B7[ 14] = { /* code 00B7, MIDDLE DOT */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00B8[ 14] = { /* code 00B8, CEDILLA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  _XX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_00B9[ 14] = { /* code 00B9, SUPERSCRIPT ONE */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00BA[ 14] = { /* code 00BA, MASCULINE ORDINAL INDICATOR */
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  __XX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00BB[ 14] = { /* code 00BB, RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  __X_X___,
  ___X_X__,
  __X_X___,
  _X_X____,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00BC[ 28] = { /* code 00BC, VULGAR FRACTION ONE QUARTER */
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  _XX___X_,________,
  __X___X_,________,
  __X__X__,_X______,
  _XXX_X__,XX______,
  ____X__X,_X______,
  ____X__X,XXX_____,
  ___X____,_X______,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00BD[ 28] = { /* code 00BD, VULGAR FRACTION ONE HALF */
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  _XX___X_,________,
  __X___X_,________,
  __X__X_X,XXX_____,
  _XXX_X__,__X_____,
  ____X___,_X______,
  ____X___,X_______,
  ___X___X,XXX_____,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00BE[ 28] = { /* code 00BE, VULGAR FRACTION THREE QUARTERS */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,X_______,
  ____X__X,________,
  __XX___X,________,
  ____X_X_,_X______,
  _XXX__X_,XX______,
  _____X_X,_X______,
  _____X_X,XXX_____,
  ____X___,_X______,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00BF[ 14] = { /* code 00BF, INVERTED QUESTION MARK */
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  _X__X___,
  __XX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00C0[ 28] = { /* code 00C0, LATIN CAPITAL LETTER A WITH GRAVE */
  __X_____,________,
  ___X____,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C1[ 28] = { /* code 00C1, LATIN CAPITAL LETTER A WITH ACUTE */
  ____X___,________,
  ___X____,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C2[ 28] = { /* code 00C2, LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
  ___XX___,________,
  __X__X__,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C3[ 28] = { /* code 00C3, LATIN CAPITAL LETTER A WITH TILDE */
  ___XX_X_,________,
  __X__X__,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C4[ 28] = { /* code 00C4, LATIN CAPITAL LETTER A WITH DIAERESIS */
  ________,________,
  __X__X__,________,
  ________,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C5[ 28] = { /* code 00C5, LATIN CAPITAL LETTER A WITH RING ABOVE */
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  ___XX___,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  __XXXX__,________,
  _X____X_,________,
  _X____X_,________,
  XXX__XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C6[ 28] = { /* code 00C6, LATIN CAPITAL LETTER AE */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXX_____,
  ___X__X_,__X_____,
  __X___X_,________,
  __X___XX,XX______,
  __XXXXX_,________,
  _X____X_,________,
  _X____X_,__X_____,
  XXX__XXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00C7[ 14] = { /* code 00C7, LATIN CAPITAL LETTER C WITH CEDILLA */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  X_____X_,
  X_______,
  X_______,
  X_______,
  _X____X_,
  __XXXX__,
  ____X___,
  __XX____,
  ________};

const unsigned char acGUI_FontGeorgia14_00C8[ 14] = { /* code 00C8, LATIN CAPITAL LETTER E WITH GRAVE */
  __X_____,
  ___X____,
  ________,
  XXXXXX__,
  _X___X__,
  _X______,
  _XXXX___,
  _X______,
  _X___X__,
  _X___X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00C9[ 14] = { /* code 00C9, LATIN CAPITAL LETTER E WITH ACUTE */
  ____X___,
  ___X____,
  ________,
  XXXXXX__,
  _X___X__,
  _X______,
  _XXXX___,
  _X______,
  _X___X__,
  _X___X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00CA[ 14] = { /* code 00CA, LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
  ___X____,
  __X_X___,
  ________,
  XXXXXX__,
  _X___X__,
  _X______,
  _XXXX___,
  _X______,
  _X___X__,
  _X___X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00CB[ 14] = { /* code 00CB, LATIN CAPITAL LETTER E WITH DIAERESIS */
  ________,
  _X__X___,
  ________,
  XXXXXX__,
  _X___X__,
  _X______,
  _XXXX___,
  _X______,
  _X___X__,
  _X___X__,
  XXXXXX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00CC[ 14] = { /* code 00CC, LATIN CAPITAL LETTER I WITH GRAVE */
  X_______,
  _X______,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00CD[ 14] = { /* code 00CD, LATIN CAPITAL LETTER I WITH ACUTE */
  __X_____,
  _X______,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00CE[ 14] = { /* code 00CE, LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
  _X______,
  X_X_____,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00CF[ 14] = { /* code 00CF, LATIN CAPITAL LETTER I WITH DIAERESIS */
  ________,
  X_X_____,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00D0[ 14] = { /* code 00D0, LATIN CAPITAL LETTER ETH */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  XXXX__X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00D1[ 28] = { /* code 00D1, LATIN CAPITAL LETTER N WITH TILDE */
  ___XX_X_,________,
  __X__X__,________,
  ________,________,
  XX___XXX,________,
  _XX___X_,________,
  _X_X__X_,________,
  _X_X__X_,________,
  _X__X_X_,________,
  _X__X_X_,________,
  _X___XX_,________,
  XXX___X_,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D2[ 28] = { /* code 00D2, LATIN CAPITAL LETTER O WITH GRAVE */
  ___X____,________,
  ____X___,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D3[ 28] = { /* code 00D3, LATIN CAPITAL LETTER O WITH ACUTE */
  ____X___,________,
  ___X____,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D4[ 28] = { /* code 00D4, LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
  ___XX___,________,
  __X__X__,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D5[ 28] = { /* code 00D5, LATIN CAPITAL LETTER O WITH TILDE */
  ___XX_X_,________,
  __X__X__,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D6[ 28] = { /* code 00D6, LATIN CAPITAL LETTER O WITH DIAERESIS */
  ________,________,
  __X__X__,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X______X,________,
  X______X,________,
  X______X,________,
  X______X,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D7[ 14] = { /* code 00D7, MULTIPLICATION SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X___X__,
  __X_X___,
  ___X____,
  __X_X___,
  _X___X__,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00D8[ 28] = { /* code 00D8, LATIN CAPITAL LETTER O WITH STROKE */
  ________,________,
  ________,________,
  ________,________,
  __XXXX_X,________,
  _X____X_,________,
  X____X_X,________,
  X___X__X,________,
  X__X___X,________,
  X_X____X,________,
  _X____X_,________,
  X_XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00D9[ 28] = { /* code 00D9, LATIN CAPITAL LETTER U WITH GRAVE */
  ___X____,________,
  ____X___,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00DA[ 28] = { /* code 00DA, LATIN CAPITAL LETTER U WITH ACUTE */
  ____X___,________,
  ___X____,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00DB[ 28] = { /* code 00DB, LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
  ___XX___,________,
  __X__X__,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00DC[ 28] = { /* code 00DC, LATIN CAPITAL LETTER U WITH DIAERESIS */
  ________,________,
  __X__X__,________,
  ________,________,
  XXX__XXX,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00DD[ 14] = { /* code 00DD, LATIN CAPITAL LETTER Y WITH ACUTE */
  ____X___,
  ___X____,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00DE[ 14] = { /* code 00DE, LATIN CAPITAL LETTER THORN */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00DF[ 14] = { /* code 00DF, LATIN SMALL LETTER SHARP S */
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X_X____,
  _X__X___,
  _X___X__,
  _X___X__,
  _X___X__,
  XX_XX___,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E0[ 14] = { /* code 00E0, LATIN SMALL LETTER A WITH GRAVE */
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E1[ 14] = { /* code 00E1, LATIN SMALL LETTER A WITH ACUTE */
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E2[ 14] = { /* code 00E2, LATIN SMALL LETTER A WITH CIRCUMFLEX */
  ________,
  ________,
  __XX____,
  _X__X___,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E3[ 14] = { /* code 00E3, LATIN SMALL LETTER A WITH TILDE */
  ________,
  ________,
  _XX_X___,
  X__X____,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E4[ 14] = { /* code 00E4, LATIN SMALL LETTER A WITH DIAERESIS */
  ________,
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E5[ 14] = { /* code 00E5, LATIN SMALL LETTER A WITH RING ABOVE */
  ________,
  __X_____,
  _X_X____,
  __X_____,
  ________,
  _XXX____,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_XX__,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E6[ 28] = { /* code 00E6, LATIN SMALL LETTER AE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,________,
  ____X___,X_______,
  _XXXXXXX,X_______,
  X___X___,________,
  X___X___,X_______,
  _XXX_XXX,________,
  ________,________,
  ________,________,
  ________,________};

const unsigned char acGUI_FontGeorgia14_00E7[ 14] = { /* code 00E7, LATIN SMALL LETTER C WITH CEDILLA */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___X___,
  X_______,
  X_______,
  X___X___,
  _XXX____,
  ___X____,
  _XX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_00E8[ 14] = { /* code 00E8, LATIN SMALL LETTER E WITH GRAVE */
  ________,
  ________,
  _X______,
  __X_____,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00E9[ 14] = { /* code 00E9, LATIN SMALL LETTER E WITH ACUTE */
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00EA[ 14] = { /* code 00EA, LATIN SMALL LETTER E WITH CIRCUMFLEX */
  ________,
  ________,
  __XX____,
  _X__X___,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00EB[ 14] = { /* code 00EB, LATIN SMALL LETTER E WITH DIAERESIS */
  ________,
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00EC[ 14] = { /* code 00EC, LATIN SMALL LETTER I WITH GRAVE */
  ________,
  ________,
  X_______,
  _X______,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00ED[ 14] = { /* code 00ED, LATIN SMALL LETTER I WITH ACUTE */
  ________,
  ________,
  __X_____,
  _X______,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00EE[ 14] = { /* code 00EE, LATIN SMALL LETTER I WITH CIRCUMFLEX */
  ________,
  ________,
  _X______,
  X_X_____,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00EF[ 14] = { /* code 00EF, LATIN SMALL LETTER I WITH DIAERESIS */
  ________,
  ________,
  ________,
  X_X_____,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F0[ 14] = { /* code 00F0, LATIN SMALL LETTER ETH */
  ________,
  _X_X____,
  __X_____,
  _X_X____,
  ____X___,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F1[ 14] = { /* code 00F1, LATIN SMALL LETTER N WITH TILDE */
  ________,
  ________,
  __XX_X__,
  _X__X___,
  ________,
  XX_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F2[ 14] = { /* code 00F2, LATIN SMALL LETTER O WITH GRAVE */
  ________,
  ________,
  _X______,
  __X_____,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F3[ 14] = { /* code 00F3, LATIN SMALL LETTER O WITH ACUTE */
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F4[ 14] = { /* code 00F4, LATIN SMALL LETTER O WITH CIRCUMFLEX */
  ________,
  ________,
  __XX____,
  _X__X___,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F5[ 14] = { /* code 00F5, LATIN SMALL LETTER O WITH TILDE */
  ________,
  ________,
  _XX_X___,
  X__X____,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F6[ 14] = { /* code 00F6, LATIN SMALL LETTER O WITH DIAERESIS */
  ________,
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F7[ 14] = { /* code 00F7, DIVISION SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  _XXXXX__,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F8[ 14] = { /* code 00F8, LATIN SMALL LETTER O WITH STROKE */
  ________,
  ________,
  ________,
  ________,
  ____X___,
  _XXX____,
  X__XX___,
  X_X_X___,
  X_X_X___,
  XX__X___,
  _XXX____,
  X_______,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00F9[ 14] = { /* code 00F9, LATIN SMALL LETTER U WITH GRAVE */
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00FA[ 14] = { /* code 00FA, LATIN SMALL LETTER U WITH ACUTE */
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00FB[ 14] = { /* code 00FB, LATIN SMALL LETTER U WITH CIRCUMFLEX */
  ________,
  ________,
  ___XX___,
  __X__X__,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00FC[ 14] = { /* code 00FC, LATIN SMALL LETTER U WITH DIAERESIS */
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

const unsigned char acGUI_FontGeorgia14_00FD[ 14] = { /* code 00FD, LATIN SMALL LETTER Y WITH ACUTE */
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  _XX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_00FE[ 14] = { /* code 00FE, LATIN SMALL LETTER THORN */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____,
  ________};

const unsigned char acGUI_FontGeorgia14_00FF[ 14] = { /* code 00FF, LATIN SMALL LETTER Y WITH DIAERESIS */
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  _XX_____,
  ________};

const GUI_CHARINFO GUI_FontGeorgia14_CharInfo[(0xff-0x20)+1] = {
   {   3,   3,  1, acGUI_FontGeorgia14_0020 } /* code 0020 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_0021 } /* code 0021 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0023 } /* code 0023 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0024 } /* code 0024 */
  ,{  10,  10,  2, acGUI_FontGeorgia14_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0026 } /* code 0026 */
  ,{   2,   2,  1, acGUI_FontGeorgia14_0027 } /* code 0027 */
  ,{   5,   5,  1, acGUI_FontGeorgia14_0028 } /* code 0028 */
  ,{   5,   5,  1, acGUI_FontGeorgia14_0029 } /* code 0029 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_002A } /* code 002A */
  ,{   7,   7,  1, acGUI_FontGeorgia14_002B } /* code 002B */
  ,{   4,   4,  1, acGUI_FontGeorgia14_002C } /* code 002C */
  ,{   4,   4,  1, acGUI_FontGeorgia14_002D } /* code 002D */
  ,{   4,   4,  1, acGUI_FontGeorgia14_002E } /* code 002E */
  ,{   5,   5,  1, acGUI_FontGeorgia14_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0030 } /* code 0030 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0039 } /* code 0039 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_003A } /* code 003A */
  ,{   4,   4,  1, acGUI_FontGeorgia14_003B } /* code 003B */
  ,{   7,   7,  1, acGUI_FontGeorgia14_003C } /* code 003C */
  ,{   7,   7,  1, acGUI_FontGeorgia14_003D } /* code 003D */
  ,{   7,   7,  1, acGUI_FontGeorgia14_003E } /* code 003E */
  ,{   6,   6,  1, acGUI_FontGeorgia14_003F } /* code 003F */
  ,{  11,  11,  2, acGUI_FontGeorgia14_0040 } /* code 0040 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_0041 } /* code 0041 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0044 } /* code 0044 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0045 } /* code 0045 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0046 } /* code 0046 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_0047 } /* code 0047 */
  ,{  10,  10,  2, acGUI_FontGeorgia14_0048 } /* code 0048 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_0049 } /* code 0049 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_FontGeorgia14_004B } /* code 004B */
  ,{   7,   7,  1, acGUI_FontGeorgia14_004C } /* code 004C */
  ,{  10,  10,  2, acGUI_FontGeorgia14_004D } /* code 004D */
  ,{   9,   9,  2, acGUI_FontGeorgia14_004E } /* code 004E */
  ,{   9,   9,  2, acGUI_FontGeorgia14_004F } /* code 004F */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0050 } /* code 0050 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0052 } /* code 0052 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0054 } /* code 0054 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_0055 } /* code 0055 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_0056 } /* code 0056 */
  ,{  12,  12,  2, acGUI_FontGeorgia14_0057 } /* code 0057 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0059 } /* code 0059 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_005A } /* code 005A */
  ,{   5,   5,  1, acGUI_FontGeorgia14_005B } /* code 005B */
  ,{   5,   5,  1, acGUI_FontGeorgia14_005C } /* code 005C */
  ,{   5,   5,  1, acGUI_FontGeorgia14_005D } /* code 005D */
  ,{   7,   7,  1, acGUI_FontGeorgia14_005E } /* code 005E */
  ,{   7,   7,  1, acGUI_FontGeorgia14_005F } /* code 005F */
  ,{   6,   6,  1, acGUI_FontGeorgia14_0060 } /* code 0060 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0061 } /* code 0061 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0062 } /* code 0062 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_0063 } /* code 0063 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0064 } /* code 0064 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_0065 } /* code 0065 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_0066 } /* code 0066 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0068 } /* code 0068 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_0069 } /* code 0069 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_006A } /* code 006A */
  ,{   7,   7,  1, acGUI_FontGeorgia14_006B } /* code 006B */
  ,{   4,   4,  1, acGUI_FontGeorgia14_006C } /* code 006C */
  ,{  12,  12,  2, acGUI_FontGeorgia14_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_FontGeorgia14_006E } /* code 006E */
  ,{   6,   6,  1, acGUI_FontGeorgia14_006F } /* code 006F */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0070 } /* code 0070 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_0071 } /* code 0071 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_0072 } /* code 0072 */
  ,{   5,   5,  1, acGUI_FontGeorgia14_0073 } /* code 0073 */
  ,{   5,   5,  1, acGUI_FontGeorgia14_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0076 } /* code 0076 */
  ,{  10,  10,  2, acGUI_FontGeorgia14_0077 } /* code 0077 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_0079 } /* code 0079 */
  ,{   5,   5,  1, acGUI_FontGeorgia14_007A } /* code 007A */
  ,{   6,   6,  1, acGUI_FontGeorgia14_007B } /* code 007B */
  ,{   4,   4,  1, acGUI_FontGeorgia14_007C } /* code 007C */
  ,{   6,   6,  1, acGUI_FontGeorgia14_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_FontGeorgia14_007E } /* code 007E */
  ,{   3,   3,  1, acGUI_FontGeorgia14_00A0 } /* code 00A0 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00A1 } /* code 00A1 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00A2 } /* code 00A2 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00A3 } /* code 00A3 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00A4 } /* code 00A4 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00A5 } /* code 00A5 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00A6 } /* code 00A6 */
  ,{   5,   5,  1, acGUI_FontGeorgia14_00A7 } /* code 00A7 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00A8 } /* code 00A8 */
  ,{  10,  10,  2, acGUI_FontGeorgia14_00A9 } /* code 00A9 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00AA } /* code 00AA */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00AB } /* code 00AB */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00AC } /* code 00AC */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00AD } /* code 00AD */
  ,{  10,  10,  2, acGUI_FontGeorgia14_00AE } /* code 00AE */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00AF } /* code 00AF */
  ,{   5,   5,  1, acGUI_FontGeorgia14_00B0 } /* code 00B0 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00B1 } /* code 00B1 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B2 } /* code 00B2 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B3 } /* code 00B3 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B4 } /* code 00B4 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B5 } /* code 00B5 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B6 } /* code 00B6 */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00B7 } /* code 00B7 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B8 } /* code 00B8 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00B9 } /* code 00B9 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00BA } /* code 00BA */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00BB } /* code 00BB */
  ,{  12,  12,  2, acGUI_FontGeorgia14_00BC } /* code 00BC */
  ,{  12,  12,  2, acGUI_FontGeorgia14_00BD } /* code 00BD */
  ,{  12,  12,  2, acGUI_FontGeorgia14_00BE } /* code 00BE */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00BF } /* code 00BF */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00C0 } /* code 00C0 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00C1 } /* code 00C1 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00C2 } /* code 00C2 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00C3 } /* code 00C3 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00C4 } /* code 00C4 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00C5 } /* code 00C5 */
  ,{  12,  12,  2, acGUI_FontGeorgia14_00C6 } /* code 00C6 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00C7 } /* code 00C7 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00C8 } /* code 00C8 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00C9 } /* code 00C9 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00CA } /* code 00CA */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00CB } /* code 00CB */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00CC } /* code 00CC */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00CD } /* code 00CD */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00CE } /* code 00CE */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00CF } /* code 00CF */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00D0 } /* code 00D0 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D1 } /* code 00D1 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D2 } /* code 00D2 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D3 } /* code 00D3 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D4 } /* code 00D4 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D5 } /* code 00D5 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D6 } /* code 00D6 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00D7 } /* code 00D7 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D8 } /* code 00D8 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00D9 } /* code 00D9 */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00DA } /* code 00DA */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00DB } /* code 00DB */
  ,{   9,   9,  2, acGUI_FontGeorgia14_00DC } /* code 00DC */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00DD } /* code 00DD */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00DE } /* code 00DE */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00DF } /* code 00DF */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00E0 } /* code 00E0 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00E1 } /* code 00E1 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00E2 } /* code 00E2 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00E3 } /* code 00E3 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00E4 } /* code 00E4 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00E5 } /* code 00E5 */
  ,{  10,  10,  2, acGUI_FontGeorgia14_00E6 } /* code 00E6 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00E7 } /* code 00E7 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00E8 } /* code 00E8 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00E9 } /* code 00E9 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00EA } /* code 00EA */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00EB } /* code 00EB */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00EC } /* code 00EC */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00ED } /* code 00ED */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00EE } /* code 00EE */
  ,{   4,   4,  1, acGUI_FontGeorgia14_00EF } /* code 00EF */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F0 } /* code 00F0 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00F1 } /* code 00F1 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F2 } /* code 00F2 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F3 } /* code 00F3 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F4 } /* code 00F4 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F5 } /* code 00F5 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F6 } /* code 00F6 */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00F7 } /* code 00F7 */
  ,{   6,   6,  1, acGUI_FontGeorgia14_00F8 } /* code 00F8 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00F9 } /* code 00F9 */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00FA } /* code 00FA */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00FB } /* code 00FB */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00FC } /* code 00FC */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00FD } /* code 00FD */
  ,{   7,   7,  1, acGUI_FontGeorgia14_00FE } /* code 00FE */
  ,{   8,   8,  1, acGUI_FontGeorgia14_00FF } /* code 00FF */
};

const FONT_T FONT_GEORGIA14 = {
	GUI_FontGeorgia14_CharInfo,14
};
